version: 2
jobs:
  build:
    docker:
      - image: golang:1.10
    working_directory: /go/src/github.com/akupila/go-wasm
    steps:
      - checkout

      - run:
          name: Test
          command: |
            go test ./...

      - run:
          name: Build
          environment:
            CGO_ENABLED: 0
          command: |
            go build -ldflags="-s -w" ./cmd/gowasm

      - run:
          name: Parse helloworld
          command: |
            ./gowasm -file ./testdata/helloworld.wasm
